apiVersion: v1
kind: ServiceAccount
metadata:
  name: train-ticket-deploy-sa
  namespace: train-ticket

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: train-ticket-deploy-role
rules:
  - apiGroups: [""]  # Core API group
    resources: ["pods", "pods/exec", "services", "configmaps", "secrets", "serviceaccounts", "persistentvolumes", "persistentvolumeclaims", "namespaces", "replicationcontrollers"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "replicasets", "daemonsets"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings", "clusterroles", "clusterrolebindings"]
    verbs: ["get", "list", "watch", "create", "update", "delete", "bind", "escalate"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: train-ticket-deploy-rolebinding
subjects:
  - kind: ServiceAccount
    name: train-ticket-deploy-sa
    namespace: train-ticket
roleRef:
  kind: ClusterRole
  name: train-ticket-deploy-role
  apiGroup: rbac.authorization.k8s.io